import { EngineContext, ActionItem, DiagnosticReport } from '../types';
import { evaluateRegulatoryExposure } from '../rules/ai-act-exposure';
import { evaluateGovernanceMaturity } from '../rules/governance-maturity';
import { evaluateTransparency } from '../rules/transparency';
import { determineNextStep } from '../prioritization/nextStepEngine';

/**
 * The Master Calculator function.
 * Acts as a pure function: takes contextual data and computes the 3 KPIs
 * and delegates to the prioritization engine.
 */
export function calculateDiagnosticReport(context: EngineContext): DiagnosticReport {
    // 1. Evaluate all rules
    const exposureResult = evaluateRegulatoryExposure(context);
    const maturityResult = evaluateGovernanceMaturity(context);
    const transparencyResult = evaluateTransparency(context);

    // 2. Aggregate all actions generated by the rules
    const allActions: ActionItem[] = [
        ...exposureResult.actions,
        ...maturityResult.actions,
        ...transparencyResult.actions
    ];

    // 3. Delegate to Prioritization Engine to determine primary/secondary splits
    const recommendations = determineNextStep(allActions);

    return {
        indices: {
            exposure: exposureResult.index,
            maturity: maturityResult.index,
            transparency: transparencyResult.index
        },
        recommendations
    };
}
